### ISSUE TITLE
[GenshinKitchen] Strange behavior relative to RESET signal

### ISSUE THREAD

**Issue by KouHiiChan** [Yan-ice/GenshinKitchen_2023F#6]
<img width="670" alt="屏幕截图 2023-12-24 230958" src="https://github.com/Yan-ice/GenshinKitchen_2023F/assets/131244549/b460db01-6226-465e-bb11-85b1c648c56c">
<img width="661" alt="屏幕截图 2023-12-24 232509" src="https://github.com/Yan-ice/GenshinKitchen_2023F/assets/131244549/40029919-b39f-43de-89fc-6acfe56061de">

If continuous pressing reset button (P15),  the client may select machine #63 with a small probability. This can happen at the first time you press the reset button as well.

However, even though I input a constant signal(8'h01), which means the client should IGNORE this signal, when keep pressing reset button, it will select #63 with a small probability.

I think there may be something wrong with UART module.

**Comment by Yan-ice** [comment]
Thanks for your issue!~
It seems that the client may receive **0xff (8'b111111_11)** from your development board when pressing the reset button. Since this may be some invalid data from the UART initialization process, I think it is really my fault to get the software to parse 0xff.

**Comment by KouHiiChan** [comment]
Thanks!
